import { Experience } from "@/types/resume/Experience";

// Responsibilities
// Technologies

export const EXPERIENCES: Experience[] = [
  {
    company: "Pitang",
    link: "",
    badges: ["Remote", "Full-Time"],
    title: "Software Engineer",
    logo: undefined,
    start: "Sep 2022",
    end: undefined,
    contents: [
      {
        title: "Responsibilities",
        description:
          "Originally hired by BBChain and transitioned to Pitang following its acquisition, I work within the Labs team, focused on building MVPs and scalable digital products for clients ranging from startups to enterprise organizations. My role spans frontend engineering and occasional full-stack contributions, adapting quickly to diverse challenges and domains. I work across various industries—finance, education, healthcare, cryptoassets, and public services—delivering fast, reliable solutions under tight deadlines. My ability to shift between technologies and problem spaces helps accelerate innovation and reduce time-to-market.",
      },
      {
        title: "Technologies",
        items: [
          "HTML",
          "CSS",
          "JavaScript",
          "TypeScript",
          "React",
          "AI (LLM)",
          "Lovable",
          "React Query",
          "Tailwind CSS",
          "Angular",
          "React Native",
          "Expo",
          "Zustand",
          "Vite",
          "Shadcn UI",
          "Next.js",
          "Nuxt.js",
          "Material UI",
          "Playwright",
          "Flutter",
          "Flutterflow",
          "Dart",
          "Firebase",
          "Styled Components",
          "Micro Frontends",
          "Modules Federation",
          "Bpmn-js",
          "Bpmn-js forms",
          "VueJs",
          "Python",
          "React Form Hooks",
          "Bootstrap 4",
          "Bootstrap 5",
        ],
      },
    ],
  },

  {
    company: "BBChain",
    link: "https://guru.com",
    badges: ["Remote", "Full-Time"],
    title: "Frotend Software Engineer",
    logo: undefined,
    start: "Oct 2020",
    end: "Sep 2022",
    contents: [
      {
        title: "Responsibilities",
        description:
          "At BBChain, a pioneer in corporate blockchain solutions, I contributed to the development of web and mobile applications for large-scale clients across finance, cryptoassets, and enterprise platforms. My role focused on building robust, scalable frontends using modern frameworks and tools, while collaborating with cross-functional teams to deliver secure and high-performance products.",
      },
      {
        title: "Technologies",
        items: [
          "HTML",
          "CSS",
          "JavaScript",
          "TypeScript",
          "React",
          "Styled Components",
          "React Native",
          "Bootstrap",
          "Redux Core",
          "Chakra UI",
          "Redux Toolkit",
          "Next.js",
          "Next translate",
          "Micro Frontends",
          "Nx",
          "Yarn workspaces",
          "Mantine UI",
          "Vite",
          "React Form Hooks",
          "React i18next",
        ],
      },
    ],
  },
  {
    company: "Deal",
    link: "https://deal.com.br",
    badges: ["Remote", "Freelance"],
    title: "Frontend Engineer Consultant",
    logo: undefined,
    start: "Jan 2020",
    end: "Jun 2020",
    contents: [
      {
        title: "Responsibilities",
        description:
          "I helped transform client needs into digital solutions by applying agile methodologies and modern frontend technologies. I worked on multiple web applications for well-known brands, contributing to the development of scalable, user-focused interfaces that supported business goals across e-commerce, insurance, and loyalty platforms.",
      },
      {
        title: "Technologies",
        items: ["HTML", "CSS", "JavaScript", "React", "Redux Core"],
      },
    ],
  },
  {
    company: "Ateliê de Software",
    link: "https://atelie.software",
    badges: ["Office", "Full-Time"],
    title: "Full Stack Engineer",
    logo: undefined,
    start: "Feb 2019",
    end: "Oct 2020",
    contents: [
      {
        title: "Responsibilities",
        description:
          "I contributed to the development of digital solutions for medium and large companies across various industries. My role involved implementing new features and building web and mobile applications using modern technologies, always within agile teams focused on delivering value quickly and efficiently.",
      },
      {
        title: "Technologies",
        items: [
          "HTML",
          "CSS",
          "JavaScript",
          "Webpack",
          "React",
          "Redux Core",
          "Styled Components",
          "Ruby",
          "Ruby on Rails",
          "React Native",
          "Expo",
          "MobX",
          "Nuxt.js",
          "Styled Components",
          "Tailwind CSS",
        ],
      },
    ],
  },
  {
    company: "Grupo Soitic",
    link: "https://soitic.com.br/",
    badges: ["Office", "Full-Time"],
    title: "Full Stack Engineer",
    logo: undefined,
    start: "Nov 2015",
    end: "Apr 2017",
    contents: [
      {
        title: "Responsibilities",
        description:
          "Led the modernization of legacy medical software into a scalable, web-based solution that improved operational efficiency and positively impacted over 30,000 healthcare professionals. Collaborated with stakeholders to assess technical feasibility and align development with market and user needs.",
      },
      {
        title: "Technologies",
        items: [
          "HTML",
          "CSS",
          "JavaScript",
          "AngularJS",
          "JQuery",
          "Bootstrap",
          ".NET Framework",
          "ASP.NET",
          "C#",
          "SQL Server",
        ],
      },
    ],
  },
];
