import { Project } from "@/types/resume/Project";

export const PROJECTS: Project[] = [
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "AI (LLM)",
      "Lovable",
      "React Query",
      "Tailwind CSS",
    ],
    title: `Informa`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `The objective was to make a proof of concept of a legacy Desktop Application (Delphi) to a web application (SPA) using AI tools to accelerate the process. The result was a success, with a millionary investment.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: ["HTML", "CSS", "JavaScript", "TypeScript", "Angular"],
    title: `Anbima - SELIC`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Dashboard for viewing transaction status for participants registered with the bank, providing this information in the best possible way to end users.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "React Native",
      "Tailwind CSS",
      "Expo",
    ],
    title: `SOLA (mobile)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Medical internship management system that automates the creation and distribution of schedules, offering an intuitive interface for students, preceptors, and coordinators. The mobile is restricted to students and preceptors, allowing them to view their schedules and mark attendance.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Zustand",
      "React Query",
      "Vite",
      "Shadcn UI",
    ],
    title: `SOLA (web)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Medical internship management system that automates the creation and distribution of schedules, offering an intuitive interface for students, preceptors, and coordinators. The web is restricted to coordinators, allowing them to create and manage schedules, as well as view attendance.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Zustand",
      "React Query",
      "Tailwind CSS",
      "Next.js",
      "Shadcn UI",
    ],
    title: `Consensus Legalização`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Complete, efficient and secure management of the entire real state regularization cycle`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Material UI",
      "Vite",
    ],
    title: `Wealth`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Portfolio composition based on the investor's profile with a pre-defined contract in which positions the broker can invest and Carrying out simulations of what the portfolio would look like based on what the client chooses based on an investment`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Zustand",
      "React Query",
      "Tailwind CSS",
      "Vite",
      "Shadcn UI",
      "Playwright",
    ],
    title: `Cad Único`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Brazilian government data and information collection system that aims to identify all low-income families in the country for inclusion in social assistance and income redistribution programs.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Zustand",
      "React Query",
      "Tailwind CSS",
      "Vite",
      "Shadcn UI",
    ],
    title: `Carteira de Estudantes (Admin and Student)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `School system where the school registers and verifies student ID requests. The student requests the issuance of their student ID and pay.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: ["Flutter", "Flutterflow", "Dart", "Firebase"],
    title: `Prefeitura Jaboatão (Client)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Appointments and services.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: ["Flutter", "Flutterflow", "Dart", "Firebase"],
    title: `Prefeitura Jaboatão (Admin)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Appointments and services.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: ["Flutter", "Flutterflow", "Dart", "Firebase"],
    title: `Fabulista`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Creation of personalized and illustrated stories with AI.`,
  },

  // 15 - 30

  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: ["Flutter", "Flutterflow", "Dart", "Firebase"],
    title: `Stanley's veins`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Marketplace for trading medical products.`,
  },
  {
    company: `B3 Digitas`,
    link: `https://b3digitas.com/`,
    image: "/b3_digitas_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Styled Components",
      "Vite",
      "Micro Frontends",
      "Modules Federation",
    ],
    title: `B3 Digitas`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `B2B and B2B2C infrastructure and solutions for the cryptoasset ecosystem, covering tokenization, trading, settlement and custody of digital assets.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Vite",
      "Bpmn-js",
      "Bpmn-js forms",
    ],
    title: `IDI-Bpm`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Process management.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Vite",
    ],
    title: `AeC (Admin)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Customer relationship, service consultancy.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "VueJs",
      "Vite",
      "Python",
    ],
    title: `Propig`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Financial management and benefits platform.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Material UI",
      "Vite",
      "React Form Hooks",
    ],
    title: `P2F`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Document management and process automation.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Bootstrap 4",
      "Vite",
    ],
    title: `Lucree (Online Checkout)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Payment link generator.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Bootstrap 4",
      "Vite",
    ],
    title: `Lucree (Onboarding)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Company accreditation to enable commission and percentage on customer sales.`,
  },
  {
    company: `Pitang`,
    link: `https://www.pitang.com/`,
    image: "/pitang_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Bootstrap 4",
      "Bootstrap 5",
      "Vite",
    ],
    title: `Lucree (Portal)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Payment and sales solutions for the following segments: automotive, workshops and auto parts, construction materials, and doctors and dentists.`,
  },
  {
    company: `BBChain`,
    link: `https://www.bbchain.com.br/`,
    image: "/bbchain_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Mantine UI",
      "Vite",
      "React Form Hooks",
      "React i18next",
    ],
    title: `BBChain`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Website of the company that specializes in corporate Blockchain technology. Was built in a week.`,
  },
  {
    company: `BBChain`,
    link: `https://www.bbchain.com.br/`,
    image: "/bbchain_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Chakra UI",
      "Redux Toolkit",
      "Next.js",
      "Next translate",
      "Micro Frontends",
      "Nx",
      "Yarn workspaces",
    ],
    title: `BlockchainLab`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `SaaS platform for creating and managing Blockchain networks.`,
  },
  {
    company: `BBChain`,
    link: `https://www.bbchain.com.br/`,
    image: "/bbchain_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Bootstrap",
      "Redux Core",
    ],
    title: `OTC`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Trading of digital assets on the over-the-counter market based on blockchain.`,
  },
  {
    company: `BBChain`,
    link: `https://www.bbchain.com.br/`,
    image: "/bbchain_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "React Native",
      "Styled Components",
    ],
    title: `Bvm12 (App and web)`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Buying and selling on the stock exchange.`,
  },
  {
    company: `BBChain`,
    link: `https://www.bbchain.com.br/`,
    image: "/bbchain_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React",
      "Styled Components",
    ],
    title: `Valluri`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Commodity negotiations, financial contracts between banks and companies.`,
  },
  {
    company: `Ateliê de Software`,
    link: `https://atelie.software/`,
    image: "/atelie_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Tailwind CSS",
      "Ruby",
      "Ruby on Rails",
    ],
    title: `W1 consultoria`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Financial planning and consulting`,
  },

  // 30 - 45

  {
    company: `Ateliê de Software`,
    link: `https://atelie.software/`,
    image: "/atelie_logo.jpg",
    badges: ["HTML", "CSS", "JavaScript", "Nuxt.js", "Tailwind CSS"],
    title: `Webgoal`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Implementation of the company's initial website.`,
  },
  {
    company: `Ateliê de Software`,
    link: `https://atelie.software/`,
    image: "/atelie_logo.jpg",
    badges: ["HTML", "CSS", "JavaScript", "Nuxt.js", "Styled Components"],
    title: `Ateliê de software`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Implementation of the company's initial website.`,
  },
  {
    company: `Deal`,
    link: `https://www.deal.com.br/`,
    image: "/deal_logo.jpg",
    badges: ["HTML", "CSS", "JavaScript", "React", "Redux Core"],
    title: `Compra Agora Unilever`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Developed an online store offering exclusive discounts for retailers.`,
  },
  {
    company: `Deal`,
    link: `https://www.deal.com.br/`,
    image: "/deal_logo.jpg",
    badges: ["HTML", "CSS", "JavaScript", "React", "Redux Core"],
    title: `Vamo Junto HDI Seguros`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Created a rewards catalog enabling hiring managers from the LTM Group to exchange points for prizes.`,
  },
  {
    company: `Ateliê de Software`,
    link: `https://atelie.software/`,
    image: "/atelie_logo.jpg",
    badges: ["HTML", "CSS", "JavaScript", "React Native", "Expo", "MobX"],
    title: `Granatum`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Implementation of an app (Android and iOS) for financial management of companies.`,
  },
  {
    company: `Ateliê de Software`,
    link: `https://atelie.software/`,
    image: "/atelie_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "Webpack",
      "React",
      "Redux Core",
      "Styled Components",
      "Ruby",
      "Ruby on Rails",
    ],
    title: `Vagas.com`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Implementation of an internal chat between contractor and participants.`,
  },
  {
    company: `Grupo SOITIC`,
    link: `https://soitic.com.br/`,
    image: "/soitic_logo.jpg",
    badges: [
      "HTML",
      "CSS",
      "JavaScript",
      "AngularJS",
      "JQuery",
      "Bootstrap",
      ".NET Framework",
      "ASP.NET",
      "C#",
      "SQL Server",
    ],
    title: `Medsystem Cloud`,
    logo: undefined,
    start: undefined,
    end: undefined,
    description: `Transformation of a legacy software into a cutting-edge solution using modern web technologies. This involved assessing technical feasibility and collaborating with stakeholders to align with market needs. The new solution positively impacted over 30,000 doctors.`,
  },
];
