interface Skill {
  name: string;
  years: number;
}

const skillsByYears: { [key: number]: string[] } = {
  0: [],
  1: [
    "Angular.js",
    "Angular",
    "Radix UI",
    "Headless UI",
    "Claude 4 Sonnet",
    "Claude 3.5 Sonnet",
    "Python",
    "TypeORM",
    "PNPM",
    "GitHub Actions",
    "MobX",
    "Module Federation",
    "Java",
  ],
  2: [
    "Webpack",
    "Vercel",
    "Shadcn UI",
    "Ruby",
    "Ruby on Rails",
    "Apollo GraphQL",
    "Apollo Server",
    "Apollo Client",
    "Microservices",
    "C#",
    "SQL Server",
    "Entity Framework",
    "ASP.NET",
    "ASP.NET Core",
  ],
  3: ["Docker"],
  4: [
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "Nest.js",
    "React Query",
    "Zustand",
    "Vite",
    "Rollup",
    "PostgreSQL",
  ],
  5: [
    "GitLab",
    "YARN",
    "MUI",
    "Material Design",
    "Material UI/UX",
    "Chakra UI",
    "Storybook",
  ],
  6: [
    "Axios",
    "GitHub",
    "BitBucket",
    "Linux",
    "TypeScript",
    "Redux Toolkit",
    "React Native",
    "React Router",
    "React Context",
    "React Hooks",
    "Tailwind UI",
    "Tailwind CSS",
    "Adobe XD",
    "Figma",
    "Zod",
    "Yup",
    "Jest",
    "Mocha",
    "Chai",
    "Azure",
    "CI/CD",
  ],
  7: [
    "HTML5",
    "CSS3",
    "Fetch",
    "React.js",
    "Styled Components",
    "Web Components",
    "Kanban",
    "Redux Core",
    "RESTful APIs",
    "Agile",
    "Scrum",
    "SASS",
    "SCSS",
  ],
  8: ["JavaScript", "Git", "SQL", "NPM", "HTML", "CSS", "Bootstrap"],
};

export const SKILLS: Skill[] = Object.entries(skillsByYears).flatMap(
  ([years, skills]) =>
    skills.filter(Boolean).map((name) => ({ name, years: Number(years) }))
);
